name: "Run tests"

on:
  push:
    branches: [ master, main, MobyDocker ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
